[buildPlans.IosevkaCustom]
family = "Iosevka agx"
spacing = "fontconfig-mono"
serifs = "sans"
noCvSs = true
exportGlyphNames = false

[buildPlans.IosevkaCustom.ligations]
inherits = "dlig"

[buildPlans.IosevkaCustom.variants]
inherits = "ss12"

[buildPlans.IosevkaCustom.variants.design]
one = "base-long-top-serif"
two = "curly-neck-serifless"
three = "flat-top-serifless"
four = "semi-open-non-crossing-serifless"
five = "upright-flat-serifless"
six = "closed-contour"
seven = "curly-serifed"
eight = "crossing-asymmetric"
nine = "straight-bar"
zero = "slashed"
capital-a = "round-top-serifless"
capital-d = "more-rounded-serifless"
capital-g = "toothless-corner-serifless-hooked"
capital-h = "serifless"
capital-j = "serifed"
capital-l = "motion-serifed"
capital-n = "standard-serifless"
capital-q = "crossing-baseline"
capital-w = "straight-vertical-sides-serifless"
j = "diagonal-tailed-serifed"
k = "straight-top-left-serifed"
l = "tailed-serifed"
m = "earless-rounded-double-arch-serifless"
n = "earless-rounded-straight-serifless"
q = "earless-rounded-straight-serifless"
r = "earless-rounded-serifless"
p = "earless-rounded-serifless"
s = "serifless"
t = "flat-hook-asymmetric-short-neck2"
u = "toothless-rounded-serifless"
w = "rounded-vertical-sides-flat-top-serifless"
z = "straight-top-serifed"
long-s = "bent-hook-bottom-serifed"
lower-eta = "earless-rounded-serifless"
lower-theta = "diamond"
lower-xi = "rounded"
cyrl-a = "double-storey-serifless"
cyrl-ve = "cursive"
cyrl-capital-ka = "curly-serifless"
cyrl-ka = "curly-serifless"
cyrl-en = "tailed-serifed"
cyrl-capital-zhe = "symmetric-connected"
cyrl-capital-er = "closed-serifless"
cyrl-er = "earless-rounded-serifless"
cyrl-el = "straight"
cyrl-capital-u = "cursive-serifless"
cyrl-u = "cursive-serifless"
cyrl-yeri = "round"
cyrl-yery = "round"
cyrl-capital-ya = "straight-serifless"
punctuation-dot = "round"
braille-dot = "round"
tilde = "low"
asterisk = "penta-low"
underscore = "high"
caret = "low"
paren = "large-contour"
brace = "straight"
number-sign = "slanted-open"
ampersand = "upper-open"
at = "threefold"
percent = "rings-segmented-slash"
bar = "natural-slope"
question = "corner-flat-hooked"
decorative-angle-brackets = "middle"
lig-ltgteq = "slanted"
lig-neq = "vertical-dotted"
lig-equal-chain = "without-notch"
lig-hyphen-chain = "without-notch"
lig-plus-chain = "without-notch"
lig-double-arrow-bar = "without-notch"
lig-single-arrow-bar = "without-notch"

[buildPlans.IosevkaCustom.weights.Regular]
shape = 400
menu = 400
css = 400

[buildPlans.IosevkaCustom.weights.Bold]
shape = 700
menu = 700
css = 700

[buildPlans.IosevkaCustom.weights.Medium]
shape = 500
menu = 500
css = 500

[buildPlans.IosevkaCustom.widths.Normal]
shape = 500
menu = 5
css = "normal"

[buildPlans.IosevkaCustom.widths.Extended]
shape = 600
menu = 7
css = "expanded"

[buildPlans.IosevkaCustom.widths.UltraExtended]
shape = 720
menu = 9
css = "ultra-expanded"

[buildPlans.IosevkaCustom.slopes.Upright]
angle = 0
shape = "upright"
menu = "upright"
css = "normal"

[buildPlans.IosevkaCustom.slopes.Italic]
angle = 9.4
shape = "italic"
menu = "italic"
css = "italic"
